package org.advent.year2024

import org.scalatest.funsuite.AnyFunSuite
import org.scalatest.matchers.should.Matchers

class Day8Test extends AnyFunSuite with Matchers {
  test("Test Day 8 Part 1") {
    val data = s"""|............
                   |........0...
                   |.....0......
                   |.......0....
                   |....0.......
                   |......A.....
                   |............
                   |............
                   |........A...
                   |.........A..
                   |............
                   |............""".stripMargin.split("\n").toList

    Day8.solution1(Day8.setup(data)) shouldBe 14
  }

  test("Test Day 8 Part 2") {
    val data = s"""|............
                   |........0...
                   |.....0......
                   |.......0....
                   |....0.......
                   |......A.....
                   |............
                   |............
                   |........A...
                   |.........A..
                   |............
                   |............""".stripMargin.split("\n").toList

    Day8.solution2(Day8.setup(data)) shouldBe 32
  }

  test("Run Day 8") {
    if (sys.env.getOrElse("PRODUCTION_RUN_DAYS", "").contains("DAY8")) Day8.run()
  }
}
