# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create New Advent of Code Source files for the Day

on:
  schedule:
    - cron: "0 5 1-25 12 *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Year and Day
        id: extract-year-day
        run: |
          year=$(echo "${GITHUB_REF#refs/heads/}" | cut -d '/' -f 2)
          day=$(echo "${GITHUB_REF#refs/heads/}" | cut -d '/' -f 3)
          echo "::set-output name=year::$year"
          echo "::set-output name=day::$day"

      - name: Copy and Replace Template
        run: |
          aoc_year=${{ steps.extract-year-day.outputs.year }}
          aoc_day=${{ steps.extract-year-day.outputs.day }}
          sed "s/{{ aoc_year }}/$aoc_year/g; s/{{ aoc_day }}/$aoc_day/g" "src/main/scala/templates/SolutionTemplate.tpl" > "src/main/scala/org/advent/yeaar$aoc_year/Day$aoc_day.scala"

      # sed "s/{{ aoc_year }}/${{ steps.extract-year-day.outputs.year }}/g; s/{{ aoc_day }}/${{ steps.extract-year-day.outputs.year }}/g" "src/main/scala/templates/SolutionTemplate.tpl" > "src/main/scala/org/advent/yeaar{{ aoc_year }}/Day{{ aoc_day }}.scala"

      # - uses: actions-template/actions-template@v1
      #   with:
      #     template: 'test/main/scala/template/SolutionTemplate.tpl'
      #     output: 'test/main/org/advent/year${{ env.AOC_YEAR }}/Day${{ env.AOC_DAY }}.scala'
      #     variables:
      #       year: ${{ steps.extract-year-day.outputs.year }}
      #       day: ${{ steps.extract-year-day.outputs.day }}

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Daily Aoc Source Files"
          add: .
