# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create New Advent of Code Source files for the Day

on:
  schedule:
    - cron: "0 5 1-25 12 *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    env:
      AOC_YEAR: 2024
      AOC_DAY: 11
    steps:
      - uses: actions/checkout@v4
      - uses: actions-template/actions-template@v1
        with:
          template: 'src/main/scala/template/SolutionTemplate.tpl'
          output: 'src/main/org/advent/year${{ env.AOC_YEAR }}/Day${{ env.AOC_DAY }}.scala'
          variables:
            aoc_day: ${{ env.AOC_DAY }}
            aoc_year: ${{ env.AOC_YEAR }}
      - uses: actions-template/actions-template@v1
        with:
          template: 'test/main/scala/template/SolutionTemplate.tpl'
          output: 'test/main/org/advent/year${{ env.AOC_YEAR }}/Day${{ env.AOC_DAY }}.scala'
          variables:
            aoc_day: ${{ env.AOC_DAY }}
            aoc_year: ${{ env.AOC_YEAR }}
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Daily Aoc Source Files"
          add: .
