# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create New Advent of Code Source files for the Day

on:
  schedule:
    - cron: "0 5 1-25 12 *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Year and Day
        id: extract-year-day
        run: |
          year=$(echo "${GITHUB_REF#refs/heads/}" | cut -d '/' -f 2)
          day=$(echo "${GITHUB_REF#refs/heads/}" | cut -d '/' -f 3)
          echo "::set-output name=year::$year"
          echo "::set-output name=day::$day"

      - uses: actions-template/actions-template@v1
        with:
          template: 'src/main/scala/template/SolutionTemplate.tpl'
          output: 'src/main/org/advent/year${{ env.AOC_YEAR }}/Day${{ env.AOC_DAY }}.scala'
          variables:
            year: ${{ steps.extract-year-day.outputs.year }}
            day: ${{ steps.extract-year-day.outputs.day }}

      - uses: actions-template/actions-template@v1
        with:
          template: 'test/main/scala/template/SolutionTemplate.tpl'
          output: 'test/main/org/advent/year${{ env.AOC_YEAR }}/Day${{ env.AOC_DAY }}.scala'
          variables:
            year: ${{ steps.extract-year-day.outputs.year }}
            day: ${{ steps.extract-year-day.outputs.day }}

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Daily Aoc Source Files"
          add: .
