# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create New Advent of Code Source files for the Day

on:
  schedule:
    - cron: "0 5 1-25 12 *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  copy-template-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Extract Year and Day
        run: |
          echo "AOC_DAY=$(date +"%-d")" >> ${GITHUB_ENV}
          echo "AOC_YEAR=$(date +%Y)" >> ${GITHUB_ENV}

      - name: Make directory and files
        run: |
          mkdir -p "src/main/scala/org/advent/year$AOC_YEAR" "src/test/scala/org/advent/year$AOC_YEAR"
          touch "src/main/scala/org/advent/year$AOC_YEAR/Day$AOC_DAY.scala" "src/test/scala/org/advent/year$AOC_YEAR/Day$AOC_DAYTest.scala"

      - name: Copy and Replace Source Template
        run: |
          cp "src/main/scala/templates/SolutionTemplate.tpl" "src/main/scala/org/advent/year$AOC_YEAR/Day$AOC_DAY.scala"
          sed -i "s/{{ aoc_year }}/$AOC_YEAR/g "src/main/scala/org/advent/year$AOC_YEAR/Day$AOC_DAY.scala"
          sed -i s/{{ aoc_day }}/$AOC_DAY/g" "src/main/scala/org/advent/year$AOC_YEAR/Day$AOC_DAY.scala"

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Daily Aoc Source Files"
          add: .
